# Site wide configuration
title: "Greater Toronto Jiu-Jitsu"
subtitle: "GTJJ"
description: "GTJJ - Modern Day Self Defence"
logo: gtjj.png # 120x120 px default image used for Twitter summary card
teaser: gtjj.png # 400x250 px default teaser image used in image archive grid
bannerimg: gtjj.png
locale: en
url: http://gtjj.ca
feed:
  path: atom.xml

# Contact Info
email: greatertorontojj@gmail.com
phone: "9058825907"
organization: "Centre for Martial Arts"
address: "Centre for Martial Arts,
Richmond Hill Campus
2 Hunter's Point, Lower level"
city: Richmond Hill
state: Ontario
country: Canada
zip_code: "L4C 9Y5"

# Contact Form Destination
contactform: https://lro66w36u9.execute-api.us-east-1.amazonaws.com/dev

# Subscribe Form Destination
subscribeurl: https://m2oqwwi6i3.execute-api.us-east-1.amazonaws.com/dev

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - html-proofer
  - jekyll-seo-tag
  - jekyll-twitter-plugin

# Site owner
owner:
  name: Phillip Robbind
  email: Phillip.Robbins1@gmail.com


# For Social Media
social:
  twitter:
  facebook:
  youtube:

# For Google Analytics
analytics-google: 'UA-109999698-1'

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
